apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelraft-node3
  namespace: travelraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travelraft
      node: node3
  template:
    metadata:
      labels:
        app: travelraft
        node: node3
    spec:
      containers:
        - name: server
          image: travelraft:latest
          imagePullPolicy: Never
          command: ["./travelraft-server"]
          args: ["--id=node3", "--port=50053"]
          ports:
            - containerPort: 50053
          env:
            - name: TRAVELRAFT_ENV
              value: kubernetes
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: travelraft
            - name: NODE_ID
              value: node3
            - name: PORT
              value: "50053"
          readinessProbe:
            tcpSocket:
              port: 50053
            initialDelaySeconds: 5
            periodSeconds: 5
