// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: api/proto/booking.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleType   string                 `protobuf:"bytes,1,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_proto_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *SearchRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SearchRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicles      []*Vehicle             `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_proto_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

type Vehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VehicleType   string                 `protobuf:"bytes,2,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	VehicleNumber string                 `protobuf:"bytes,3,opt,name=vehicle_number,json=vehicleNumber,proto3" json:"vehicle_number,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,6,opt,name=destination,proto3" json:"destination,omitempty"`
	DepartureTime string                 `protobuf:"bytes,7,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_api_proto_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_proto_rawDescGZIP(), []int{2}
}

func (x *Vehicle) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vehicle) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *Vehicle) GetVehicleNumber() string {
	if x != nil {
		return x.VehicleNumber
	}
	return ""
}

func (x *Vehicle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vehicle) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Vehicle) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Vehicle) GetDepartureTime() string {
	if x != nil {
		return x.DepartureTime
	}
	return ""
}

type GetSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     int32                  `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatsRequest) Reset() {
	*x = GetSeatsRequest{}
	mi := &file_api_proto_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatsRequest) ProtoMessage() {}

func (x *GetSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatsRequest.ProtoReflect.Descriptor instead.
func (*GetSeatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_proto_rawDescGZIP(), []int{3}
}

func (x *GetSeatsRequest) GetVehicleId() int32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

type GetSeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seats         []*Seat                `protobuf:"bytes,1,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatsResponse) Reset() {
	*x = GetSeatsResponse{}
	mi := &file_api_proto_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatsResponse) ProtoMessage() {}

func (x *GetSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatsResponse.ProtoReflect.Descriptor instead.
func (*GetSeatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_proto_rawDescGZIP(), []int{4}
}

func (x *GetSeatsResponse) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

type Seat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VehicleId     int32                  `protobuf:"varint,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	SeatNumber    string                 `protobuf:"bytes,3,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_api_proto_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_proto_rawDescGZIP(), []int{5}
}

func (x *Seat) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Seat) GetVehicleId() int32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *Seat) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *Seat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassengerName string                 `protobuf:"bytes,1,opt,name=passenger_name,json=passengerName,proto3" json:"passenger_name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	VehicleId     int32                  `protobuf:"varint,3,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	SeatId        int32                  `protobuf:"varint,4,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookRequest) Reset() {
	*x = BookRequest{}
	mi := &file_api_proto_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRequest) ProtoMessage() {}

func (x *BookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRequest.ProtoReflect.Descriptor instead.
func (*BookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_proto_rawDescGZIP(), []int{6}
}

func (x *BookRequest) GetPassengerName() string {
	if x != nil {
		return x.PassengerName
	}
	return ""
}

func (x *BookRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BookRequest) GetVehicleId() int32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *BookRequest) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

type BookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Pnr           string                 `protobuf:"bytes,2,opt,name=pnr,proto3" json:"pnr,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookResponse) Reset() {
	*x = BookResponse{}
	mi := &file_api_proto_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookResponse) ProtoMessage() {}

func (x *BookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookResponse.ProtoReflect.Descriptor instead.
func (*BookResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_proto_rawDescGZIP(), []int{7}
}

func (x *BookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BookResponse) GetPnr() string {
	if x != nil {
		return x.Pnr
	}
	return ""
}

func (x *BookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pnr           string                 `protobuf:"bytes,1,opt,name=pnr,proto3" json:"pnr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_api_proto_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_proto_rawDescGZIP(), []int{8}
}

func (x *GetBookingRequest) GetPnr() string {
	if x != nil {
		return x.Pnr
	}
	return ""
}

type GetBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Booking       *Booking               `protobuf:"bytes,2,opt,name=booking,proto3" json:"booking,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingResponse) Reset() {
	*x = GetBookingResponse{}
	mi := &file_api_proto_booking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingResponse) ProtoMessage() {}

func (x *GetBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingResponse.ProtoReflect.Descriptor instead.
func (*GetBookingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_proto_rawDescGZIP(), []int{9}
}

func (x *GetBookingResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetBookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

func (x *GetBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pnr           string                 `protobuf:"bytes,2,opt,name=pnr,proto3" json:"pnr,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VehicleId     int32                  `protobuf:"varint,4,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	SeatId        int32                  `protobuf:"varint,5,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	PassengerName string                 `protobuf:"bytes,6,opt,name=passenger_name,json=passengerName,proto3" json:"passenger_name,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	VehicleName   string                 `protobuf:"bytes,8,opt,name=vehicle_name,json=vehicleName,proto3" json:"vehicle_name,omitempty"`
	VehicleNumber string                 `protobuf:"bytes,9,opt,name=vehicle_number,json=vehicleNumber,proto3" json:"vehicle_number,omitempty"`
	SeatNumber    string                 `protobuf:"bytes,10,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_api_proto_booking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_proto_rawDescGZIP(), []int{10}
}

func (x *Booking) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Booking) GetPnr() string {
	if x != nil {
		return x.Pnr
	}
	return ""
}

func (x *Booking) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Booking) GetVehicleId() int32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *Booking) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *Booking) GetPassengerName() string {
	if x != nil {
		return x.PassengerName
	}
	return ""
}

func (x *Booking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Booking) GetVehicleName() string {
	if x != nil {
		return x.VehicleName
	}
	return ""
}

func (x *Booking) GetVehicleNumber() string {
	if x != nil {
		return x.VehicleNumber
	}
	return ""
}

func (x *Booking) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pnr           string                 `protobuf:"bytes,1,opt,name=pnr,proto3" json:"pnr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_api_proto_booking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_proto_rawDescGZIP(), []int{11}
}

func (x *CancelRequest) GetPnr() string {
	if x != nil {
		return x.Pnr
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_api_proto_booking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_booking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_booking_proto_rawDescGZIP(), []int{12}
}

func (x *CancelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_booking_proto protoreflect.FileDescriptor

const file_api_proto_booking_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/booking.proto\x12\abooking\"l\n" +
	"\rSearchRequest\x12!\n" +
	"\fvehicle_type\x18\x01 \x01(\tR\vvehicleType\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\">\n" +
	"\x0eSearchResponse\x12,\n" +
	"\bvehicles\x18\x01 \x03(\v2\x10.booking.VehicleR\bvehicles\"\xd8\x01\n" +
	"\aVehicle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12!\n" +
	"\fvehicle_type\x18\x02 \x01(\tR\vvehicleType\x12%\n" +
	"\x0evehicle_number\x18\x03 \x01(\tR\rvehicleNumber\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x06 \x01(\tR\vdestination\x12%\n" +
	"\x0edeparture_time\x18\a \x01(\tR\rdepartureTime\"0\n" +
	"\x0fGetSeatsRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\x05R\tvehicleId\"7\n" +
	"\x10GetSeatsResponse\x12#\n" +
	"\x05seats\x18\x01 \x03(\v2\r.booking.SeatR\x05seats\"n\n" +
	"\x04Seat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\x05R\tvehicleId\x12\x1f\n" +
	"\vseat_number\x18\x03 \x01(\tR\n" +
	"seatNumber\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x82\x01\n" +
	"\vBookRequest\x12%\n" +
	"\x0epassenger_name\x18\x01 \x01(\tR\rpassengerName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x03 \x01(\x05R\tvehicleId\x12\x17\n" +
	"\aseat_id\x18\x04 \x01(\x05R\x06seatId\"T\n" +
	"\fBookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03pnr\x18\x02 \x01(\tR\x03pnr\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"%\n" +
	"\x11GetBookingRequest\x12\x10\n" +
	"\x03pnr\x18\x01 \x01(\tR\x03pnr\"p\n" +
	"\x12GetBookingResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12*\n" +
	"\abooking\x18\x02 \x01(\v2\x10.booking.BookingR\abooking\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xa6\x02\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03pnr\x18\x02 \x01(\tR\x03pnr\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x04 \x01(\x05R\tvehicleId\x12\x17\n" +
	"\aseat_id\x18\x05 \x01(\x05R\x06seatId\x12%\n" +
	"\x0epassenger_name\x18\x06 \x01(\tR\rpassengerName\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12!\n" +
	"\fvehicle_name\x18\b \x01(\tR\vvehicleName\x12%\n" +
	"\x0evehicle_number\x18\t \x01(\tR\rvehicleNumber\x12\x1f\n" +
	"\vseat_number\x18\n" +
	" \x01(\tR\n" +
	"seatNumber\"!\n" +
	"\rCancelRequest\x12\x10\n" +
	"\x03pnr\x18\x01 \x01(\tR\x03pnr\"D\n" +
	"\x0eCancelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc3\x02\n" +
	"\x0eBookingService\x129\n" +
	"\x06Search\x12\x16.booking.SearchRequest\x1a\x17.booking.SearchResponse\x12?\n" +
	"\bGetSeats\x12\x18.booking.GetSeatsRequest\x1a\x19.booking.GetSeatsResponse\x123\n" +
	"\x04Book\x12\x14.booking.BookRequest\x1a\x15.booking.BookResponse\x12E\n" +
	"\n" +
	"GetBooking\x12\x1a.booking.GetBookingRequest\x1a\x1b.booking.GetBookingResponse\x129\n" +
	"\x06Cancel\x12\x16.booking.CancelRequest\x1a\x17.booking.CancelResponseB\x1cZ\x1atravelraft/api/proto;protob\x06proto3"

var (
	file_api_proto_booking_proto_rawDescOnce sync.Once
	file_api_proto_booking_proto_rawDescData []byte
)

func file_api_proto_booking_proto_rawDescGZIP() []byte {
	file_api_proto_booking_proto_rawDescOnce.Do(func() {
		file_api_proto_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_booking_proto_rawDesc), len(file_api_proto_booking_proto_rawDesc)))
	})
	return file_api_proto_booking_proto_rawDescData
}

var file_api_proto_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_booking_proto_goTypes = []any{
	(*SearchRequest)(nil),      // 0: booking.SearchRequest
	(*SearchResponse)(nil),     // 1: booking.SearchResponse
	(*Vehicle)(nil),            // 2: booking.Vehicle
	(*GetSeatsRequest)(nil),    // 3: booking.GetSeatsRequest
	(*GetSeatsResponse)(nil),   // 4: booking.GetSeatsResponse
	(*Seat)(nil),               // 5: booking.Seat
	(*BookRequest)(nil),        // 6: booking.BookRequest
	(*BookResponse)(nil),       // 7: booking.BookResponse
	(*GetBookingRequest)(nil),  // 8: booking.GetBookingRequest
	(*GetBookingResponse)(nil), // 9: booking.GetBookingResponse
	(*Booking)(nil),            // 10: booking.Booking
	(*CancelRequest)(nil),      // 11: booking.CancelRequest
	(*CancelResponse)(nil),     // 12: booking.CancelResponse
}
var file_api_proto_booking_proto_depIdxs = []int32{
	2,  // 0: booking.SearchResponse.vehicles:type_name -> booking.Vehicle
	5,  // 1: booking.GetSeatsResponse.seats:type_name -> booking.Seat
	10, // 2: booking.GetBookingResponse.booking:type_name -> booking.Booking
	0,  // 3: booking.BookingService.Search:input_type -> booking.SearchRequest
	3,  // 4: booking.BookingService.GetSeats:input_type -> booking.GetSeatsRequest
	6,  // 5: booking.BookingService.Book:input_type -> booking.BookRequest
	8,  // 6: booking.BookingService.GetBooking:input_type -> booking.GetBookingRequest
	11, // 7: booking.BookingService.Cancel:input_type -> booking.CancelRequest
	1,  // 8: booking.BookingService.Search:output_type -> booking.SearchResponse
	4,  // 9: booking.BookingService.GetSeats:output_type -> booking.GetSeatsResponse
	7,  // 10: booking.BookingService.Book:output_type -> booking.BookResponse
	9,  // 11: booking.BookingService.GetBooking:output_type -> booking.GetBookingResponse
	12, // 12: booking.BookingService.Cancel:output_type -> booking.CancelResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_booking_proto_init() }
func file_api_proto_booking_proto_init() {
	if File_api_proto_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_booking_proto_rawDesc), len(file_api_proto_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_booking_proto_goTypes,
		DependencyIndexes: file_api_proto_booking_proto_depIdxs,
		MessageInfos:      file_api_proto_booking_proto_msgTypes,
	}.Build()
	File_api_proto_booking_proto = out.File
	file_api_proto_booking_proto_goTypes = nil
	file_api_proto_booking_proto_depIdxs = nil
}
